This is the customer model
Marcus-Johnson/NJInsurancePlatform pull request #5
Opened 2022-10-26 21:47 UTC by AbelRodriguezGuillen

2022-10-26 21:51 UTC, Marcus-Johnson requested changes
Please make changes and review other Pull Requests.

2022-10-26 21:51 UTC, Marcus-Johnson commented on NJInsurancePlatform/Models/CustomerModel.cs
> +        [Key]
Add [ScaffoldColumn(false)] so we cannot edit primary key

2022-10-26 21:51 UTC, Marcus-Johnson commented on NJInsurancePlatform/Models/CustomerModel.cs
> +        [Key]
You need to look at the current Policy Model https://github.com/Marcus-Johnson/NJInsurancePlatform/pull/4/files PolicyMUID is spelled differently and is a GUID

2022-10-26 21:51 UTC, Marcus-Johnson commented on NJInsurancePlatform/Models/CustomerModel.cs
> +        public string FirstName { get; set; }
Add a DisplayName for each Data Type, or there will be no title in our view.

2022-10-26 22:23 UTC, Marcus-Johnson requested changes

2022-10-26 22:23 UTC, Marcus-Johnson commented on NJInsurancePlatform/Models/CustomerModel.cs
> +    public class CustomerModel
public partial Customer ?

2022-10-27 14:04 UTC, AbelRodriguezGuillen commented on NJInsurancePlatform/Models/CustomerModel.cs
> +    public class CustomerModel
You want me to change it to a partial class?

2022-10-27 14:05 UTC, AbelRodriguezGuillen commented on NJInsurancePlatform/Models/CustomerModel.cs
> +        public string FirstName { get; set; }
Will do.

2022-10-27 14:05 UTC, AbelRodriguezGuillen commented on NJInsurancePlatform/Models/CustomerModel.cs
> +        [Key]
Okay, I will add that and make adjustments to the name. Thank you.

2022-10-27 15:47 UTC, Marcus-Johnson requested changes
public class Customer not customermodel because it effects the name of the generated table

2022-10-27 16:00 UTC, merged